on:
  workflow_dispatch:
  schedule:
    - cron: 0 */12 * * *

name: Update and release

permissions: {}

jobs:
  updateDataAndRelease:
    permissions:
      contents: read # to fetch code (actions/checkout)

    name: Update data and release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Update data and release
        run: npm run release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
